### ISSUE TITLE
Spark's Tools doesn't create any config file and doesn't add anything to the game

### ISSUE THREAD

**Issue by Fireztonez** [thebrightspark/SparksTools#1]
Hello,
I really enjoy Spark's Hammer and I just saw mod that would be the successor of Spark's Hammer, but with more tools and stuff... So I remove Spark's hammer from my modpack and add Spark's Tools, but when I look in JEI, I have absolutly nothing added by Spark's Tools, and there have no config files, no JSON, no Config Folder, nothing.

The only thing I saw, in the Mod List, in Game, Spark's Tools is present, but again, no In Game Config, so, is it just me, or the mod just doesn't work at all right now??

Version:
Minecraft Forge: 1.12.2 - 14.23.5.2838
Spark's Tools: 1.0.1

I have tests on my modpack with more than 200 mods and after on a really clean instance, in both case, nothing....

Thank's

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/SparksTools/commit/8b53f32cdbcf041f91f4d86f49867e3dd4700c10
Will be fine for v1.0.2+ now
