### ISSUE TITLE
Crash with Lumberaxe

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksTools#2]
Game crashed upon attempting to use a diamond lumberaxe.

Isolated this and veinminer (to test for issues), game crashed upon using creative to put the lumberaxe in my inventory.

Report 1
-------------------------------
[crash-2019-08-23_21.15.26-client.txt](https://github.com/thebrightspark/SparksTools/files/3536739/crash-2019-08-23_21.15.26-client.txt)

Report 2
-------------------------------
[crash-2019-08-23_21.25.03-client.txt](https://github.com/thebrightspark/SparksTools/files/3536740/crash-2019-08-23_21.25.03-client.txt)

**Comment by ghost** [comment]
Additional attempt while holding a gold lumberaxe. Crash occurred while holding the axe, EXACTLY when the tree became marked as the targeted block

**Comment by thebrightspark** [comment]
Thanks, I think I see the issue. Will get this fixed asap

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/SparksTools/commit/3c0a41b8d8190e29e119a204dca20955089aaf5f

Released version 1.0.3 with the fix
